spring.profiles.active: local

spring:
    profiles: local

#ftp下载接口
ftp.download: 10.10.10.10

#ftp上传接口
ftp.upload: 10.10.10.10

#临时中转目录
local.directory.download: /home/work/release/download/

---

spring:
    profiles: online

#ftp下载接口
ftp.download: 10.10.10.10

#ftp上传接口
ftp.upload: 10.10.10.10

#临时中转目录
local.directory.download: /home/work/release/download/

cihome.receive.compile: http://localhost:8080/compileBuild/end
